// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Sleb0bo-bz5sLPa-vfe098EWEUpQrao',
    appId: '1:711832328176:web:847740192e5538e19b2f35',
    messagingSenderId: '711832328176',
    projectId: 'get-in-1a288',
    authDomain: 'get-in-1a288.firebaseapp.com',
    storageBucket: 'get-in-1a288.appspot.com',
    measurementId: 'G-VNX73CRSKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgLz63cCjgGRTRAZqJYF7hsvR2zg8kQY',
    appId: '1:711832328176:android:ff9ececba7a1e6c29b2f35',
    messagingSenderId: '711832328176',
    projectId: 'get-in-1a288',
    storageBucket: 'get-in-1a288.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSBdxpXJPjr-Vey6L4QqmsObzDyo3b5I',
    appId: '1:711832328176:ios:112d81ff6ff621019b2f35',
    messagingSenderId: '711832328176',
    projectId: 'get-in-1a288',
    storageBucket: 'get-in-1a288.appspot.com',
    androidClientId: '711832328176-t35ma28h3rjpip9bm837qv03gq9n84kl.apps.googleusercontent.com',
    iosClientId: '711832328176-conougvvogki37qoqltlhjdlmvv35slm.apps.googleusercontent.com',
    iosBundleId: 'com.example.getIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOSBdxpXJPjr-Vey6L4QqmsObzDyo3b5I',
    appId: '1:711832328176:ios:fd9b8e9737a4e4f39b2f35',
    messagingSenderId: '711832328176',
    projectId: 'get-in-1a288',
    storageBucket: 'get-in-1a288.appspot.com',
    androidClientId: '711832328176-t35ma28h3rjpip9bm837qv03gq9n84kl.apps.googleusercontent.com',
    iosClientId: '711832328176-edf9lul1uus9nbnt9u803ifauugbv2jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.getIn.RunnerTests',
  );
}
